// Subject: Shomara, Persian math for children. Job: try and inspect a 24-screen design handoff.
// Plan: counting-bead trail; original soft-volume vector cast; teal #218B92, saffron #E9A00E,
// violet #7863B9, mist #F3F8F6, ink #23373D. Persian sans text, mono screen IDs.
// Layout: [flow inspector] [mobile prototype] [character reference]. Signature: the zigzag bead trail.
// Zipline spark: design around real use. Learning, practice and identity are separate destinations.
import React,{useState,useEffect,useId} from 'react';
import {Route,Grid2X2,Shirt,UserRound,ChevronLeft,ArrowRight,Check,Lock,Star,Wifi,WifiOff,Settings,Volume2,Download,ShieldCheck,BookOpen,RefreshCw,Clock,Eye,Palette,ExternalLink} from 'lucide-react';
import {Button,ToggleGroup,ToggleGroupItem,Switch,Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter,Accordion,AccordionItem,AccordionTrigger,AccordionContent,Field,FieldGroup,FieldLabel,Select,SelectTrigger,SelectValue,SelectContent,SelectGroup,SelectItem,Progress,Skeleton} from '@kits/shadcn';
import screens from './screens.json';
import flow from './design-flow.json';
import {BASES,OPTIONS,normalizeAvatar,changeBase,readAvatar,writeAvatar,lessonResult} from './avatar-core.mjs';
import {characterSvg} from './character-art.mjs';
import './style.css';
const fa=n=>String(n).replace(/\d/g,c=>'۰۱۲۳۴۵۶۷۸۹'[c]);
const names={human:'آدمک',dragon:'اژدها',bird:'پرنده',robot:'ربات',fox:'روباه'};
const optNames={none:'بدون',curl:'فرفری',crest:'تاج مو',cap:'کپ',bucket:'سطلکی',crown:'تاج',soft:'کوچک',wide:'تاب‌دار',teal:'فیروزه‌ای',violet:'بنفش',amber:'طلایی',porcelain:'پوست ۱',sand:'پوست ۲',warm:'پوست ۳',bronze:'پوست ۴',umber:'پوست ۵',deep:'پوست ۶',dark:'تیره',brown:'قهوه‌ای',copper:'مسی'};
const cast=[{base:'dragon',color:'teal',name:'آریا',role:'نشان برند و آغاز'},{base:'robot',color:'amber',name:'کیوبو',role:'ساختن و دسته‌بندی'},{base:'bird',color:'violet',name:'دانا',role:'الگو و شکل'},{base:'fox',color:'amber',name:'جیکو',role:'بازی و جشن'}];
const tabs=[['S07','مسیر',Route],['S14','تمرین',Grid2X2],['S17','کمد',Shirt],['S19','من',UserRound]];
const questions=[{count:4,options:[3,4,5]},{count:6,options:[5,6,7]},{count:3,options:[2,3,4]}];
function Character({avatar={},size=140,pose='idle',view='front',icon=false}){
  const uid=useId().replace(/:/g,'');
  return <span className="character" style={{width:size,height:icon?size:size*256/224}} aria-hidden="true" dangerouslySetInnerHTML={{__html:characterSvg({...avatar,pose,view,icon,uid})}}/>;
}
function Action({children,onClick,disabled=false,testid,secondary=false}){return <Button className={secondary?'action secondary':'action'} variant={secondary?'outline':'default'} onClick={onClick} disabled={disabled} data-testid={testid}>{children}</Button>}
function Choice({label,value,values,onChange}){return <Field><FieldLabel>{label}</FieldLabel><ToggleGroup type="single" value={value} onValueChange={v=>v&&onChange(v)} className="choice-group" aria-label={label}>{values.map(v=><ToggleGroupItem value={v} key={v} aria-label={`${label}: ${optNames[v]||names[v]||v}`}>{optNames[v]||names[v]||v}</ToggleGroupItem>)}</ToggleGroup></Field>}
export default function App(){
  const [page,setPage]=useState('S07'),[state,setState]=useState('ready'),[offline,setOffline]=useState(false),[reduced,setReduced]=useState(false);
  const [loaded]=useState(()=>readAvatar(window.localStorage)),[saved,setSaved]=useState(loaded.avatar),[draft,setDraft]=useState(loaded.avatar);
  const [notice,setNotice]=useState(loaded.error||''),[gate,setGate]=useState(null),[discard,setDiscard]=useState(null),[adult,setAdult]=useState(false);
  const [question,setQuestion]=useState(0),[selection,setSelection]=useState(null),[feedback,setFeedback]=useState(null),[attempts,setAttempts]=useState([]),[wrong,setWrong]=useState(false),[passed,setPassed]=useState(false);
  const [grade,setGrade]=useState('۱'),[pose,setPose]=useState('idle'),[view,setView]=useState('front');
  const [downloaded,setDownloaded]=useState(true),[demoConsent,setDemoConsent]=useState(false),[avatarReturn,setAvatarReturn]=useState('S19'),[selectedItem,setSelectedItem]=useState('crown');
  const screen=screens.find(s=>s.id===page),dirty=JSON.stringify(saved)!==JSON.stringify(draft),adultPages=['S22','S23','S24'];
  const nav=(p,inspector=false)=>{if(!inspector&&p!==page&&(page==='S10'||page==='S06'&&state==='assessment')){setDiscard(p);return;}if(page==='S20'&&dirty&&p!=='S20'){setDiscard(p);return;}setPage(p);setState('ready');setNotice('');if(p==='S20'){setDraft(saved);setAvatarReturn(page==='S05'?'S05':'S19');}if(adultPages.includes(p)&&!adult)setGate(p);};
  const tabOf=p=>['S14','S15','S16'].includes(p)?'S14':['S17','S18','S20'].includes(p)?'S17':['S19','S21','S22','S23','S24'].includes(p)?'S19':'S07';
  useEffect(()=>{setReduced(window.matchMedia('(prefers-reduced-motion: reduce)').matches);document.documentElement.lang='fa';document.documentElement.dir='rtl';},[]);
  const resetLesson=()=>{setQuestion(0);setSelection(null);setFeedback(null);setWrong(false);setAttempts([]);};
  const begin=()=>{if(offline&&!downloaded){setNotice('این درس دریافت نشده. بعد از اتصال دوباره امتحان کن.');return;}resetLesson();nav('S10');};
  const checkAnswer=()=>{if(selection===null||feedback==='correct')return;const correct=selection===questions[question].count;if(page==='S06'){setAttempts(a=>[...a,{question,firstTryCorrect:correct}]);nextQuestion();return;}setFeedback(correct?'correct':'wrong');if(!correct)setWrong(true);else setAttempts(a=>[...a,{question,firstTryCorrect:!wrong}]);};
  const nextQuestion=()=>{if(question===2){if(page==='S06'){setState('assessment-complete');}else{nav('S12',true);if(!offline)setPassed(true);}}else{setQuestion(q=>q+1);setSelection(null);setFeedback(null);setWrong(false);}};
  const save=()=>{const r=writeAvatar(window.localStorage,draft);if(!r.ok){setNotice(r.error);return false;}setSaved(normalizeAvatar(draft));setPage(avatarReturn);setState('ready');setNotice(offline?'ظاهر روی این مرورگر ذخیره شد؛ این نمونه سرور همگام‌سازی ندارد.':'ظاهر روی این مرورگر ذخیره شد.');return true;};
  const result=lessonResult(attempts,3);
  const body=()=>{
    if(state==='assessment-complete')return <div className="state-demo"><h2>سنجش نمونه تمام شد</h2><p>بدون راهنما و بازخورد پاسخ. در محصول، نقطهٔ شروع را سرور تعیین می‌کند؛ اینجا تغییری در مسیر نمی‌دهیم.</p><Action onClick={()=>nav('S07')}>برگشت به مسیر</Action></div>;
    if(state==='loading')return <div className="state-demo"><Skeleton className="h-24 w-full"/><Skeleton className="h-12 w-full"/><p>داریم آماده می‌کنیم…</p></div>;
    if(state==='error')return <div className="state-demo"><RefreshCw size={40}/><h2>این بار نشد</h2><p>{page==='S20'?'ظاهر ذخیره نشده؛ تغییرها را نگه می‌داریم.':'اطلاعات هنوز آماده نیست. پیشرفت قبلی دست‌نخورده است.'}</p><Action onClick={()=>setState('ready')}>دوباره امتحان کن</Action></div>;
    if(state==='empty')return <div className="state-demo"><BookOpen size={40}/><h2>{page==='S17'?'کمدت منتظر کشف است':'هنوز چیزی اینجا نیست'}</h2><p>از یک تمرین کوتاه شروع کن.</p><Action onClick={()=>nav('S07')}>برگشت به مسیر</Action></div>;
    if(adultPages.includes(page)&&!adult)return <div className="state-demo"><ShieldCheck size={44}/><h2>فضای بزرگسال</h2><p>گیت والد فقط مرز رابط است؛ محصول به احراز هویت و مجوز سرور نیاز دارد.</p><Action onClick={()=>setGate(page)}>دیدن نمونهٔ والد</Action><Action secondary onClick={()=>nav('S19')}>بازگشت</Action></div>;
    if(page==='S07')return <>
      <button className="unit-header" onClick={()=>nav('S08')}><span className="unit-label">پایهٔ {grade} · واحد ۱</span><strong>دنیای عددها</strong><span>دیدن واحد <ChevronLeft size={18}/></span></button>
      <div className="home-mascot"><Character avatar={{base:'dragon',color:'teal'}} size={87}/><div><b>{passed?'یک قدم دیگر جلو رفتی!':'قدم بعدی تو، شمارش'}</b><p>{offline?'نسخهٔ تمرینیِ دریافت‌شده آماده است.':'کم‌کم، با کشف کردن.'}</p></div></div>
      <div className="trail"><svg className="trail-line" viewBox="0 0 300 380" preserveAspectRatio="none" aria-hidden="true"><path d="M150 42 Q250 66 230 122 T90 202 Q10 244 80 282 Q110 330 180 352" fill="none" stroke="#D4E5DE" strokeWidth="12" strokeLinecap="round" strokeDasharray="2 20"/></svg>
        {[{x:50,y:11,name:'دیدن عددها',done:true},{x:76.7,y:32.1,name:'شمارش تا شش',active:!passed,done:passed},{x:30,y:53.2,name:'ساختن گروه‌ها',active:passed},{x:26.7,y:74.2,name:'بازی جمع‌آوری'},{x:60,y:92.6,name:'کشف بعدی'}].map((n,i)=><div className="node-wrap" key={i} style={{left:n.x+'%',top:n.y+'%'}}><button data-testid={`node-${i}`} className={`node ${n.active?'active':n.done?'done':'locked'}`} aria-label={`${n.name}، ${n.done?'مرور':n.active?'شروع':'پیش‌نیاز تکمیل نشده'}`} onClick={()=>n.done||n.active?nav('S09'):setNotice(`برای «${n.name}» اول مرحلهٔ قبلی را تمام کن.`)}>{n.done?<Check/>:n.active?<Star fill="currentColor"/>:<Lock/>}</button>{n.active&&<span className="node-tag">اینجا شروع کن</span>}<span className="node-name">{n.name}</span></div>)}
      </div></>;
    if(page==='S20')return <div className="workshop"><div className="avatar-stage"><Character avatar={draft} size={153}/><span>پیش‌نمایش زنده · مستقل از یادگیری</span></div>
      <FieldGroup><Choice label="شخصیت" value={draft.base} values={BASES} onChange={v=>setDraft(a=>changeBase(a,v))}/>
      {draft.base==='human'?<Choice label="رنگ پوست" value={draft.skinTone} values={OPTIONS.skinTone} onChange={v=>setDraft(a=>({...a,skinTone:v}))}/>:<Choice label="رنگ شخصیت" value={draft.color} values={OPTIONS.color} onChange={v=>setDraft(a=>({...a,color:v}))}/>}
      <Choice label="مو و تاج" value={draft.hair} values={draft.base==='robot'?['none','crest']:OPTIONS.hair} onChange={v=>setDraft(a=>({...a,hair:v}))}/>
      <Choice label="رنگ مو و سبیل" value={draft.hairColor} values={OPTIONS.hairColor} onChange={v=>setDraft(a=>({...a,hairColor:v}))}/>
      <Choice label="کلاه" value={draft.hat} values={OPTIONS.hat} onChange={v=>setDraft(a=>({...a,hat:v}))}/>
      <Choice label={draft.base==='bird'?'نقش زیر منقار':draft.base==='dragon'?'سبیل فانتزی پوزه':'سبیل فانتزی'} value={draft.moustache} values={OPTIONS.moustache} onChange={v=>setDraft(a=>({...a,moustache:v}))}/>
      <Choice label="لباس" value={draft.outfit} values={OPTIONS.outfit} onChange={v=>setDraft(a=>({...a,outfit:v}))}/>
      <Field><div className="switch-row"><FieldLabel htmlFor="glasses">عینک</FieldLabel><Switch id="glasses" checked={draft.glasses} onCheckedChange={v=>setDraft(a=>({...a,glasses:v}))}/></div></Field>
      </FieldGroup><div className="two-actions"><Action testid="avatar-save" onClick={save}>ذخیرهٔ ظاهر</Action><Action secondary onClick={()=>{setDraft(saved);setPage(avatarReturn);setNotice('تغییرها لغو شد.');}}>لغو</Action></div></div>;
    if(page==='S19')return <div className="profile-screen"><Character avatar={saved} size={157}/><h2>کاوشگر کوچک</h2><p>پایهٔ {grade} · ظاهر مخصوص خودت</p><Action onClick={()=>nav('S20')} testid="edit-avatar"><Palette/> تغییر ظاهر</Action>
      <div className="profile-stat"><span><b>{passed?'۲':'۱'}</b> مرحلهٔ نمونه</span><span><b>{offline?'در انتظار':'آماده'}</b> وضعیت اتصال</span></div>
      <button className="list-row" onClick={()=>nav('S21')}><Settings/><span>تنظیمات</span><ChevronLeft/></button><button className="list-row" onClick={()=>setGate('S22')}><ShieldCheck/><span>فضای خانواده</span><ChevronLeft/></button><p className="small-copy">آواتار تو راهنمای درس نیست. هر کدام نقش جدا دارند.</p></div>;
    if(page==='S10'||page==='S06'&&state==='assessment')return <div className="lesson"><div className="lesson-head"><span>پرسش {fa(question+1)} از ۳</span><Progress value={(question/3)*100} aria-label="پیشرفت پرسش‌های نمونه"/></div><h2>{page==='S06'?'سنجش بدون راهنما':'چند مهره می‌بینی؟'}</h2><p>همه را بشمار، بعد یک عدد انتخاب کن.</p>
      <div className="count-area" aria-label={`${fa(questions[question].count)} مهره`}>{Array.from({length:questions[question].count},(_,i)=><span className="count-bead" key={i}/>)}</div>
      <ToggleGroup type="single" value={selection===null?'':String(selection)} onValueChange={v=>{if(v&&feedback!=='correct'){setSelection(Number(v));setFeedback(null);}}} aria-label="پاسخ شمارش" className="answer-group">{questions[question].options.map(n=><ToggleGroupItem key={n} value={String(n)} aria-label={`عدد ${fa(n)}`} data-testid={`answer-${n}`}>{fa(n)}</ToggleGroupItem>)}</ToggleGroup>
      {feedback==='wrong'&&<div className="feedback wrong" role="status">یک بار دیگر، از اولین مهره شروع کن. عجله‌ای نیست.</div>}{feedback==='correct'&&<div className="feedback correct" role="status"><Check/> آفرین، {fa(questions[question].count)} مهره است.</div>}
      {offline&&<p className="pending">نتیجهٔ این تمرین نمونه هنوز تأیید سرور نیست.</p>}<Action disabled={selection===null} testid="check-answer" onClick={feedback==='correct'?nextQuestion:checkAnswer}>{page==='S06'?'ثبت پاسخ':feedback==='correct'?'ادامه':'بررسی پاسخ'}</Action><Action secondary onClick={()=>setDiscard('S07')}>خروج از درس</Action></div>;
    if(page==='S12')return <div className="result-screen"><Character avatar={{base:'fox',color:'amber'}} pose="celebrate" size={150}/><h2>{offline?'تمرین تمام شد':'کشف امروزت کامل شد'}</h2><p>{attempts.length?`${fa(result.firstTryCorrect)} پاسخ درست در اولین تلاش از ${fa(result.total)}`:'این صفحه نمونه است؛ هنوز تمرینی انجام نشده.'}</p><div className="result-number">{attempts.length?fa(result.accuracy)+'٪':'…'}</div><span>درستیِ اولین تلاش در تمرین نمونه</span><p className="small-copy">{offline?'در محصول: پاسخ‌ها در صف می‌مانند و قفل بعدی فقط با تأیید سرور باز می‌شود.':'این پیشرفت نمایشی است، نه مدرک تسلط آموزشی یا امتیاز سرور.'}</p><Action onClick={()=>nav('S07')}>برگشت به مسیر</Action><Action secondary onClick={()=>nav('S18')}>دیدن جایزهٔ نمونه</Action></div>;
    if(page==='S14'||page==='S15')return <div className="practice-screen"><div className="section-title"><span className="eyebrow">تمرین، نه یک مسیر دوم</span><h2>یک کشف کوتاه</h2><p>بازی‌ها و مهارت‌ها یک خانه دارند.</p></div><ToggleGroup type="single" value={page} onValueChange={v=>v&&nav(v)} className="choice-group" aria-label="نوع تمرین"><ToggleGroupItem value="S14">بازی‌ها</ToggleGroupItem><ToggleGroupItem value="S15">مهارت‌ها</ToggleGroupItem></ToggleGroup>
      {(page==='S14'?[['باغ مهره‌ها','شمارش · ۳ دقیقه',Grid2X2],['پل عددها','ترتیب · ۲ دقیقه',Route]]:[['عدد و شمارش','مرور یک مفهوم',Star],['شکل و الگو','کشف با دانا',Grid2X2]]).map(([title,sub,Icon],i)=><button className="practice-card" key={title} onClick={()=>nav(page==='S14'?'S09':'S16')}><span className={i===1?'tile-icon tile-1':'tile-icon'}><Icon/></span><strong>{title}</strong><span>{sub}</span><ChevronLeft/></button>)}<p className="small-copy">بازی تمرینی مسیر آموزشی را بدون تأیید ارزیابی تغییر نمی‌دهد.</p></div>;
    if(page==='S17')return <div className="wardrobe-screen"><div className="section-title"><h2>کمد کشف‌ها</h2><p>شخصیتت را شبیه خودت بساز.</p></div><div className="mini-avatar"><Character avatar={saved} size={137}/><Action onClick={()=>nav('S20')}>کارگاه شخصیت</Action></div><h3>چیزهای کوچک، سلیقهٔ خودت</h3><div className="item-grid">{[['cap','کپ بنفش'],['bucket','کلاه طلایی'],['crown','تاج کاغذی']].map(([hat,label])=><button key={hat} onClick={()=>{setSelectedItem(hat);nav('S18');}}><Character avatar={{base:saved.base,hat}} size={75} icon/><b>{label}</b><span>آیتم نمونه</span></button>)}</div><p className="small-copy">هیچ رنگ پوست یا گونه‌ای پولی و قفل نیست. خرید فقط در فضای والد.</p></div>;
    if(page==='S21')return <div className="settings-screen"><h2>راحت‌تر یاد بگیر</h2><div className="switch-row"><span><Volume2/> صدای نمونه</span><Switch aria-label="صدای نمونه" onCheckedChange={()=>setNotice('در این بسته صدای ضبط‌شده موجود نیست.')}/></div><div className="switch-row"><span><Eye/> حرکت کمتر</span><Switch aria-label="حرکت کمتر" checked={reduced} onCheckedChange={setReduced}/></div><button className="list-row" onClick={()=>setGate('S24')}><ShieldCheck/><span>حساب خانواده</span><ChevronLeft/></button><p>فارسی · راست‌به‌چپ</p><p className="small-copy">خوانایی و معنای بازخورد در حرکت کمتر هم حفظ می‌شود.</p></div>;
    if(page==='S22')return <div className="parent-screen"><span className="eyebrow">فضای خانواده · دادهٔ نمایشی</span><h2>قدم‌های کوچک مهم‌اند</h2><p>کاوشگر کوچک · پایهٔ {grade}</p><div className="report-block"><b>شمارش تا شش</b><span>{attempts.length?`${fa(result.firstTryCorrect)} از ${fa(result.total)} در اولین تلاش`:'هنوز نتیجه‌ای در نمونه نداریم'}</span><p>این گزارش رتبه‌بندی یا تشخیص آموزشی نیست.</p></div><h3>پیشنهاد همراهی</h3><p>با هم شش وسیله پیدا کنید و بشمارید. بدون عجله، بدون مقایسه.</p><Action onClick={()=>nav('S23')}>بررسی دسترسی آموزشی</Action><Action secondary onClick={()=>nav('S24')}>مدیریت حساب</Action></div>;
    if(page==='S01')return <div className="welcome-screen"><Character avatar={{base:'dragon'}} size={200}/><h1>شمارا</h1><h2>عددها را کشف کن.</h2><p>ریاضی، یک قدم کوچک در هر روز.</p><Action onClick={()=>nav('S02')}>شروع با خانواده</Action><Action secondary onClick={()=>nav('S07')}>دیدن مسیر نمونه</Action></div>;
    if(page==='S02'||page==='S03')return <div className="generic-screen"><ShieldCheck size={46}/><h2>{screen.title}</h2><p>ابتدا فضای بزرگسال، بعد فضای کودک.</p><div className="report-block"><b>{page==='S02'?'نمونهٔ ورود، بدون اطلاعات شخصی':'کد تأیید فقط نمایشی'}</b><p>این پیش‌نمایش ایمیل، شماره، رمز یا کد واقعی دریافت نمی‌کند.</p><span>در محصول: احراز مالک و رضایت قبل از پروفایل کودک.</span></div><Action onClick={()=>nav(page==='S02'?'S03':'S04')}>ادامهٔ مسیر نمونه</Action></div>;
    if(page==='S04')return <div className="generic-screen"><h2>پایهٔ تو کدام است؟</h2><p>پیش‌فرض اجباریِ پایهٔ اول حذف می‌شود.</p><ToggleGroup type="single" value={grade} onValueChange={v=>v&&setGrade(v)} className="grade-grid" aria-label="انتخاب پایه">{['۱','۲','۳','۴','۵','۶'].map(n=><ToggleGroupItem key={n} value={n}>پایهٔ {n}</ToggleGroupItem>)}</ToggleGroup><Action onClick={()=>nav('S05')}>ادامه</Action></div>;
    if(page==='S05')return <div className="generic-screen"><Character avatar={saved} size={170}/><h2>کاوشگر کوچک</h2><p>نام نمایشی نمونه، نه نام واقعی کودک.</p><Action secondary onClick={()=>nav('S20')}>انتخاب ظاهر</Action><Action onClick={()=>nav('S06')}>ادامه به نقطهٔ شروع</Action></div>;
    if(page==='S06')return <div className="generic-screen"><h2>از کجا شروع کنیم؟</h2><p>سه پرسش کوتاه. بدون راهنما، بدون امتیاز و بدون استرس.</p><Action onClick={()=>{resetLesson();setState('assessment');}}>دیدن سنجش نمونه</Action><Action secondary onClick={()=>nav('S07')}>از ابتدا شروع می‌کنم</Action></div>;
    if(page==='S08')return <div className="generic-screen"><h2>دنیای عددها</h2><p>عددها را ببین، بشمار و دسته‌بندی کن.</p><div className="report-block"><b>۵ گام کوتاه</b><span>پیش‌نیازها روی هر مرحله مشخص‌اند.</span></div><div className="switch-row"><span><Download/> دریافت نمونه</span><Switch aria-label="درس دریافت‌شده" checked={downloaded} onCheckedChange={setDownloaded}/></div><p className="small-copy">این کلید وضعیت نمونه را شبیه‌سازی می‌کند؛ دانلود واقعی نیست.</p><Action onClick={()=>nav('S09')}>مرحلهٔ بعدی</Action></div>;
    if(page==='S09')return <div className="generic-screen"><Character avatar={{base:'robot',color:'amber'}} size={155}/><span className="eyebrow">واحد ۱ · گام ۲</span><h2>شمارش تا شش</h2><p>مهره‌ها را بشمار. حدود ۳ دقیقه.</p><div className="report-block"><Clock/><span>{offline?(downloaded?'نمونهٔ دریافت‌شده آماده است':'درس هنوز دریافت نشده'):'آمادهٔ شروع'}</span></div><Action testid="start-lesson" onClick={begin} disabled={offline&&!downloaded}>شروع تمرین نمونه</Action><Action secondary onClick={()=>nav('S07')}>برگشت به مسیر</Action></div>;
    if(page==='S16')return <div className="generic-screen"><Character avatar={{base:'bird',color:'violet'}} size={135}/><h2>هر مهره، یک عدد</h2><div className="concept-beads">{[1,2,3].map(n=><span key={n}><i className="count-bead"/><b>{fa(n)}</b></span>)}</div><p>هر چیز را یک‌بار می‌شماریم. ترتیب شمردن، تعداد را عوض نمی‌کند.</p><Action onClick={()=>nav('S09')}>امتحانش کنیم</Action></div>;
    if(page==='S18')return <div className="generic-screen"><Character avatar={{...saved,hat:selectedItem}} size={175}/><h2>{selectedItem==='cap'?'کپ بنفش':selectedItem==='bucket'?'کلاه طلایی':'تاج کاغذی'}</h2><p>یک چیز کوچک برای ظاهر مخصوص تو.</p><Action onClick={()=>{setDraft({...saved,hat:selectedItem});setAvatarReturn('S19');setPage('S20');}}>امتحان در کارگاه</Action><Action secondary onClick={()=>nav('S17')}>برگشت به کمد</Action></div>;
    if(page==='S11')return <div className="generic-screen"><Character avatar={{base:'fox',color:'amber'}} size={155}/><h2>باغ مهره‌ها</h2><p>بازی انتقال هنوز موتور مستقل ندارد. اینجا مسیر و ظاهر آن مشخص می‌شود.</p><div className="count-area">{[0,1,2,3,4].map(i=><span key={i} className="count-bead"/>)}</div><Action onClick={begin}>دیدن تعامل شمارش نمونه</Action><Action secondary onClick={()=>nav('S12')}>دیدن قالب نتیجه</Action></div>;
    if(page==='S13')return <div className="generic-screen"><Lock size={44}/><h2>آمادهٔ رفتن جلوتر هستی؟</h2><p>پرش با آزمون مستقل ممکن است، نه با خرید یا امتیاز. نمونه، پیشرفت آموزشی را تغییر نمی‌دهد.</p><Action onClick={()=>nav('S06')}>دیدن آزمون نمونه</Action></div>;
    if(page==='S23')return <div className="generic-screen"><h2>دسترسی آموزشی</h2><p>اطلاعات طرح، مبلغ و شرایط باید قبل از پرداخت روشن باشند.</p><div className="report-block"><ShieldCheck/><b>پرداخت واقعی در این نمونه موجود نیست.</b><span>قیمت، درگاه و شرایط تأیید نشده‌اند؛ هیچ دادهٔ مالی دریافت نمی‌شود.</span></div><Action secondary onClick={()=>nav('S22')}>بازگشت به گزارش</Action></div>;
    if(page==='S24')return <div className="generic-screen"><h2>حساب خانواده</h2><p>دسترسی کودک و بزرگسال جداست.</p>{['مدیریت کودک‌ها','تغییر اطلاعات ورود','خروجی داده‌ها','درخواست حذف حساب'].map(t=><div className="list-row inactive-row" key={t}><ShieldCheck/><span>{t}</span><Lock/></div>)}<p className="small-copy">عملیات حساس در نمونه غیرفعال است؛ محصول به تأیید دوباره و مجوز سرور نیاز دارد.</p><Action secondary onClick={()=>nav('S19')}>برگشت</Action></div>;
    return null;
  };
  return <div className={`studio ${reduced?'reduced':''}`} dir="rtl">
    <header className="studio-header"><div className="wordmark"><span className="brand-icon"><Character avatar={{base:'dragon'}} size={42} icon/></span><div><b>شمارا</b><span>کارگاه نهایی‌سازی طراحی</span></div></div><div className="version"><span className="live-dot"/> بازنگری ۱٫۳ <span className="badge">پیش‌نمایش طراحی، نه اپ نهایی</span></div></header>
    <main className="studio-layout">
      <aside className="inspector"><span className="eyebrow">از صفحه تا پیاده‌سازی</span><h1>یک مسیر روشن.<br/>یک دنیای خودمان.</h1><p className="intro">منطق پیشرفت دولینگو، با هویت مستقل و ریاضی فارسی. همهٔ ۲۴ قالب را ببین و مسیر اصلی را امتحان کن.</p>
        <FieldGroup><Field><FieldLabel htmlFor="screen-picker">صفحهٔ مورد بررسی</FieldLabel><Select value={page} onValueChange={p=>nav(p,true)} dir="rtl"><SelectTrigger id="screen-picker" data-testid="screen-picker"><SelectValue/></SelectTrigger><SelectContent><SelectGroup>{screens.map(s=><SelectItem key={s.id} value={s.id}>{s.id} · {s.title}</SelectItem>)}</SelectGroup></SelectContent></Select></Field>
        <Field><FieldLabel>وضعیت نمایشی</FieldLabel><ToggleGroup type="single" value={state==='assessment'?'ready':state} onValueChange={v=>v&&setState(v)} className="choice-group" aria-label="وضعیت صفحه">{[['ready','عادی'],['loading','بارگذاری'],['empty','خالی'],['error','خطا']].map(([v,t])=><ToggleGroupItem key={v} value={v}>{t}</ToggleGroupItem>)}</ToggleGroup></Field></FieldGroup>
        <div className="switch-row"><span>{offline?<WifiOff/>:<Wifi/>} شبیه‌سازی آفلاین</span><Switch aria-label="شبیه‌سازی آفلاین" checked={offline} onCheckedChange={setOffline}/></div><div className="switch-row"><span><Eye/> حرکت کمتر</span><Switch aria-label="حرکت کمتر در پیش‌نمایش" checked={reduced} onCheckedChange={setReduced}/></div>
        <div className="spec-brief"><span className="screen-id">{screen.id} / {screen.route}</span><h2>{screen.title}</h2><p>{flow.find(s=>s.id===page).flow}</p></div>
        <Accordion type="single" collapsible><AccordionItem value="states"><AccordionTrigger>حالت‌ها و دسترس‌پذیری</AccordionTrigger><AccordionContent><p>{screen.required_states}</p><p>{screen.accessibility_rtl}</p></AccordionContent></AccordionItem><AccordionItem value="audit"><AccordionTrigger>اختلاف با کد فعلی</AccordionTrigger><AccordionContent><p>{screen.observed_current}</p><p>{screen.mobile_parity}</p>{screen.issues.map((i,n)=><div className="audit-note" key={n}><b>{i.severity}</b><p>{i.finding}</p></div>)}</AccordionContent></AccordionItem></Accordion>
        <div className="journey"><b>سفر اصلی</b><p>خانواده ← پایه ← آواتار ← جایابی ← مسیر ← شروع درس ← تمرین ← نتیجه</p><button onClick={()=>nav('S01')}>از خوش‌آمد شروع کن <ChevronLeft size={18}/></button></div>
      </aside>
      <section className="prototype-column" aria-label="پیش‌نمایش موبایل"><div className="prototype-label"><span>نمونهٔ تعاملی</span><span>{screen.id} · {screen.title}</span></div>
        <div className="phone"><div className="statusbar" aria-hidden="true"><span>۹:۴۱</span><span>●●● ▰</span></div><div className="app-top"><button aria-label="بازگشت به مسیر" onClick={()=>nav('S07')}><ArrowRight size={21}/></button><b>{['S07','S01'].includes(page)?'شمارا':screen.title}</b><span className={`connection ${offline?'pending-status':''}`} title={offline?'آفلاین نمونه':'آنلاین نمونه'}>{offline?<WifiOff size={17}/>:<Wifi size={17}/>}</span></div>
          {offline&&<div className="offline-banner">آفلاینِ نمونه · تأیید آموزشی سرور شبیه‌سازی نمی‌شود</div>}
          <div className="phone-content" data-testid="screen-content" data-screen={page}>{notice&&<div className="notice" role="status">{notice}</div>}{body()}</div>
          {!(page==='S10'||page==='S06'&&state==='assessment')&&<nav className="bottom-nav" aria-label="ناوبری کودک">{tabs.map(([id,title,Icon])=><button key={id} aria-label={title} aria-current={tabOf(page)===id?'page':undefined} className={tabOf(page)===id?'selected':''} onClick={()=>nav(id)}><Icon size={24}/><span>{title}</span></button>)}</nav>}
        </div><p className="prototype-caption">ذخیرهٔ ظاهر روی همین مرورگر است. درس، حساب و جایزه دادهٔ نمونه دارند.</p>
      </section>
      <aside className="art-panel"><span className="eyebrow">نرم، حجمی، به‌یادماندنی</span><h2>آریا، این بار<br/>با هویت خودش.</h2><p>اژدهای دوستانهٔ شمارا. نه جغد دولینگو، نه گودزیلا. عمق از نور و لایه می‌آید، نه جزئیات شلوغ.</p>
        <div className="hero-character"><Character avatar={{base:'dragon',color:'teal'}} pose={pose} view={view} size={230}/><span className="art-note">مطالعهٔ برداری ۲٫۵بعدی</span></div>
        <ToggleGroup className="choice-group" type="single" value={pose} onValueChange={v=>v&&setPose(v)} aria-label="حالت آریا">{[['idle','آرام'],['think','فکر'],['celebrate','جشن']].map(([v,t])=><ToggleGroupItem key={v} value={v}>{t}</ToggleGroupItem>)}</ToggleGroup>
        <ToggleGroup className="choice-group" type="single" value={view} onValueChange={v=>v&&setView(v)} aria-label="نمای آریا">{[['front','روبه‌رو'],['quarter','سه‌رخ'],['side','مطالعهٔ عمق']].map(([v,t])=><ToggleGroupItem key={v} value={v}>{t}</ToggleGroupItem>)}</ToggleGroup>
        <div className="cast-grid">{cast.map(c=><div key={c.name}><Character avatar={c} size={82}/><b>{c.name}</b><span>{c.role}</span></div>)}</div>
        <div className="icon-study"><span className="launcher"><Character avatar={{base:'dragon'}} size={72} icon/></span><div><b>آیکون پیشنهادی</b><p>چهرهٔ آریا، بدون نوشته. خوانا در اندازهٔ کوچک.</p></div></div>
        <p className="small-copy">تصاویر SVG واقعی‌اند، نه فایل Rive. نماهای جانبی مطالعهٔ حجم‌اند، نه turnaround نهایی برای rig.</p><a className="source-link" href="https://blog.duolingo.com/developing-math/" target="_blank" rel="noreferrer">چرا Rive در ریاضی دولینگو؟ <ExternalLink size={15}/></a>
      </aside>
    </main>
    <footer className="studio-footer"><b>برای ساختن، نه فقط دیدن.</b><span>۴ تب کودک · ۲۴ قالب ممیزی‌شده · قرارداد آواتار · مسیر اصلی قابل تجربه</span></footer>
    <Dialog open={!!gate} onOpenChange={o=>{if(!o)setGate(null);}}><DialogContent dir="rtl"><DialogHeader><DialogTitle>ورود نمایشی به فضای خانواده</DialogTitle><DialogDescription>این تأیید فقط برای دیدن نمونه است، نه احراز سن، رضایت قانونی یا امنیت حساب. هیچ اطلاعات واقعی دریافت نمی‌شود.</DialogDescription></DialogHeader><div className="switch-row"><span>می‌دانم این فقط نمونهٔ طراحی است</span><Switch aria-label="تأیید نمونهٔ والد" checked={demoConsent} onCheckedChange={setDemoConsent}/></div><DialogFooter><Button disabled={!demoConsent} data-testid="adult-demo" onClick={()=>{setAdult(true);setPage(gate);setGate(null);setDemoConsent(false);}}>دیدن نمونهٔ خانواده</Button><Button variant="outline" onClick={()=>setGate(null)}>بازگشت</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={!!discard} onOpenChange={o=>{if(!o)setDiscard(null);}}><DialogContent dir="rtl"><DialogHeader><DialogTitle>{page==='S20'?'تغییرهای ظاهرت ذخیره نشده':'خروج از تمرین نمونه؟'}</DialogTitle><DialogDescription>{page==='S20'?'ظاهر قبلی تا زمان ذخیره تغییر نمی‌کند.':'در محصول، خروج باید checkpoint ذخیره کند. این نمونه جلسهٔ آموزشی واقعی ندارد.'}</DialogDescription></DialogHeader><DialogFooter>{page==='S20'&&<Button onClick={()=>{if(save())setDiscard(null);}}>ذخیرهٔ ظاهر</Button>}<Button variant="outline" onClick={()=>{setDraft(saved);setPage(discard);setState('ready');setDiscard(null);}}>خروج بدون تغییر</Button><Button variant="outline" onClick={()=>setDiscard(null)}>ادامه می‌دهم</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
